server:
  port: 8080

spring:
  application:
    name: camel-standard-architecture
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders_db}
    username: ${DB_USER:fluxaria}
    password: ${DB_PASSWORD:fluxaria_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [corrId:%X{correlationId}] - %msg%n"

camel:
  springboot:
    name: camel-standard-architecture
    main-run-controller: true
  servlet:
    mapping:
      context-path: /api/*

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

integration:
  kafka:
    brokers: ${KAFKA_BROKERS:localhost:9092}
    topic-orders-processed: orders.processed
    topic-orders-failed: orders.failed
    topic-orders-batch-in: ${KAFKA_TOPIC_BATCH_IN:orders.batch.in}
    topic-orders-batch-summary: ${KAFKA_TOPIC_BATCH_SUMMARY:orders.batch.summary}
    topic-orders-dlq: ${KAFKA_TOPIC_DLQ:orders.dlq}
    batch-consumer-group: ${KAFKA_BATCH_GROUP:fluxaria-orders-batch-group}
  outbound:
    country:
      base-url: "https://restcountries.com/v3.1/alpha"
    currency:
      base-url: "https://open.er-api.com/v6/latest"
    erp:
      base-url: ${ERP_BASE_URL:http://localhost:8080/api/mock-erp/erp/orders}
      connect-timeout-ms: 2000
      read-timeout-ms: 3000
      max-retries: 3
      retry-delay-ms: 1000
      backoff-multiplier: 2.0
      circuit-breaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state-ms: 5000
        sliding-window-size: 5